server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://harmoneydb.czqoy0e2y3u4.ap-northeast-2.rds.amazonaws.com:3306/harmoneydb?serverTimezone=UTC&useSSL=false
    username: harmoney
    password: hana9988!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: false

# ⬇️ 이 둘은 spring *바깥* 최상위여야 합니다.
jwt:
  secret: "CHANGE-ME-TO-AT-LEAST-32-BYTES-SECRET-KEY"
  ttlMillis: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
