server:
  address: 0.0.0.0
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  jackson:
    mapper:
      accept-case-insensitive-enums: true

  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

  web:
    cors:
      allowed-origins: "*"
      allowed-methods: "GET,POST,PUT,PATCH,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: false

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID:}
        secret-key: ${AWS_SECRET_ACCESS_KEY:}

jwt:
  secret: ${JWT_SECRET}
  ttlMillis: 3600000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui
    display-request-duration: true
    try-it-out-enabled: true

logging:
  level:
    root: INFO
    com.example.hanaharmonybackend: DEBUG
    org.springframework: INFO
    org.springframework.web: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket.messaging: DEBUG
    org.hibernate.SQL: DEBUG

aws:
  s3:
    bucket: ${AWS_BUCKET}
    region: ap-northeast-2

fcm:
  service-account-path: ${FCM_ACCOUNT_PATH}
  project-id: ${FCM_PROJECT_ID}

# =========================
# test 프로필(H2) 설정 추가
# =========================
---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_UPPER=false;NON_KEYWORDS=VALUE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop   # 테스트 실행 시 매번 생성/삭제
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        show_sql: false
  h2:
    console:
      enabled: true
  flyway:
    enabled: false
  liquibase:
    enabled: false
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.SQL: debug