name: Deploy to EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Add EC2 key
        run: |
          echo "${{ secrets.EC2_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Copy jar to EC2
        run: |
          scp -i key.pem -o StrictHostKeyChecking=no \
          build/libs/HanaHarmoney-backend-0.0.1-SNAPSHOT.jar \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:/home/ec2-user/app/app.jar

      - name: Restart app on EC2
        run: |
          ssh -i key.pem -o StrictHostKeyChecking=no \
          ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            pid=$(pgrep -f HanaHarmoney-backend || true)
            if [ -n "$pid" ]; then
              echo "Killing process $pid"
              kill -9 $pid
            fi
            cd /home/ec2-user/app
            nohup java -jar app.jar > app.log 2>&1 &
          EOF
